### ISSUE TITLE
feat: 把verytoolz集成进来

### ISSUE THREAD

**Issue by hapihacking** [91go/oktools#4]
[YAML在线解析](https://verytoolz.com/yaml-parser.html)

**Comment by luckyhacking** [comment]
- [ ] JSON在线编辑
- [ ] JSON在线解析
- [ ] JSON格式化
- [ ] JSON在线校验
- [ ] JSON在线压缩
- [ ] JSON在线美化
- [ ] JSON转XML
- [ ] JSON转CSV
- [ ] JSON转YAML
- [ ] JSON转TSV
- [ ] JSON转JAVA
- [ ] JSON5格式化
- [ ] JSON5在线验证
